final_time: 10
steps_n: 1000
precision: -3
nu: 0.36
rho_0: 13230
domain: custom
domain_size_x: 1
domain_size_y: 1
shelf_size_x: 0.5
shelf_size_y: 0.1
mesh_resolution: 10
mesh_resolution_x: 20
mesh_resolution_y: 4
mesh_resolution_sea_top_y: 1
store_sol: False
verbose: True
very_verbose: False
plot: True
