BCs:
  Q:
    sea_top: 0
  T:
    left: 3*x[1]
    right: 3*x[1]
  V:
    bottom:
    - 0
    - 0
    left:
    - 0
    - 0
    right:
    - 0
    - 0
    sea_top:
    - 0
    - 0
S_0: 35
T_0: 0
T_init: 3*x[1]
alpha:
- 0.01
beta: 0.0001
config_file: feffi/config/ford-experiment.yml
convert_from_ms_to_kmh: true
degree_P: 1
degree_S: 1
degree_T: 1
degree_V: 2
delta0: 1
domain: fjord
domain_size_x: 100
domain_size_y: 1
final_time: 2
g: 9.81
gamma: 0
label: ''
max_iter: 0
mesh_resolution: 20
mesh_resolution_sea_y: 4
mesh_resolution_x: 60
mesh_resolution_y: 20
non_linear_max_iter: 30
nu:
- 0.01
plot_path: /home/stefano/git/fenics-phd/plots/1620201649
rho_0: 1028.0
shelf_size_x: 0
shelf_size_y: 0
simulation_precision: -5
stabilization: false
steps_n: 10
store_solutions: true
tau0: 35
very_verbose: false
