final_time: 10
steps_n: 1000
simulation_precision: -5
degree_V: 2
degree_P: 1
degree_T: 1
degree_S: 1

convert_from_ms_to_kmh: False
g: 9.81
nu: 
- 100
alpha:
- 100
rho_0: 1028
beta: 0.0001
gamma: 0.00076
T_0: 1
S_0: 35
Omega_0: -5e-5

domain: square
domain_size_x: 2
domain_size_y: 1
shelf_size_x: 0.7
shelf_size_y: 0.1
mesh_resolution: 10
mesh_resolution_x: 20
mesh_resolution_y: 10
mesh_resolution_sea_y: 1
ice_shelf_bottom_p: (0, 0.05, 0)
ice_shelf_top_p: (5, 1, 0)
boundary_layer_thickness: 0.003

very_verbose: False
store_solutions: False
checkpoint_interval: 20

label: ''
max_iter: 0
non_linear_max_iter: 30

pressure_split: False
stabilization: False
delta0: 1
tau0: 35

BCs:
    V:
        right: ['0.5*sin(2*pi*x[1])', 0]
        bottom: [0,0]
        left: [0,0]
        top: [0,0]
    T:
        right: 3
        left: -1.9
    Q:
        '(1,1)': 0
    S:
        right: 35
        left: 34.5
melt_boundaries:
    - 
