final_time: 10
steps_n: 1000
simulation_precision: -3
g: 9.81
nu: 
- 0.01
alpha:
- 0.01
rho_0: 1028
beta: 0.0001
gamma: 0.00076
T_0: 1
S_0: 35
domain: square
mesh_resolution: 10
max_iter: 3000
BCs:
    V:
        right: [0, 0]
        bottom: [0,0]
        left: [0,0]
        top: [0,0]
    T:
        right: 1
        left: 1
    Q:
        '(1,1)': 0
    S:
        right: 35
        left: 35
