BCs:
  Q:
    '(25,0)': 0
  S:
    right: 34.5+tanh(pi * 1000*(-x[1] +0.8) / 200)/2
  T:
    right: -0.6+tanh(pi * 1000*(-x[1] +0.8) / 200)
  V:
    bottom:
    - 0
    - 0
    left:
    - 0
    - 0
    ice_shelf_top:
    - 0
    - 0
    ice_shelf_bottom:
    - 0
    - 0
    right:
    - 0
    - 0
    top:
    - 'null'
    - 0
S_0: 35
T_0: 1
alpha:
- 0.25
- 1.0e-05
beta: 4.0e-05
boundary_layer_thickness: 0.01
checkpoint_interval: 5
convert_from_ms_to_kmh: true
domain_size_x: 30
domain_size_y: 1
final_time: 240
gamma: 0.0008
ice_shelf_bottom_p:
- 0
- 0.05
- 0
ice_shelf_top_p:
- 20
- 0.95
- 0
max_iter: 300
melt_boundaries:
- ice_shelf_top
mesh_resolution: 0.04
nu:
- 0.25
- 0.001
plot_path: nosplit-boundary-damped
rho_0: 1000
simulation_precision: -3
stabilization_NS: true
stabilization_S: true
stabilization_T: true
steps_n: 30
store_solutions: true
very_verbose: false
