final_time: 240
steps_n: 30    # dt = 1/30 h = 120 s  (kimura 200 s)
simulation_precision: -7
nu: 
- 0.25
- 0.001
alpha:
- 0.25 #- 0.25
- 0.00002 #- 0.00002
rho_0: 1000
beta: 0.00004
gamma: 0.0008
T_0: 0.4
S_0: 35
max_iter: 0
BCs:
    V:
        right: [0,0]
        bottom: [0,0]
        ice_shelf: [0,0]
        left: [0,0]
        top: ['null',0]
    T:
        #ice_shelf: 0.2
        right: 0.4
    Q:
        '(20,1)': 0
    S:
        #ice_shelf: 34.85
        right: 35
melt_boundaries:
    - ice_shelf
    #- left
convert_from_ms_to_kmh: True
very_verbose: true
stabilization_NS: True
stabilization_T: true
#stabilization_T_coeff: 0.1
stabilization_S: true
#stabilization_S_coeff: 0.1
checkpoint_interval: 30
plot_path: mitgcm-melting-iceshelf
domain_size_x: 30
domain_size_y: 1
mesh_resolution: 0.5
ice_shelf_bottom_p:
- 0
- 0.05
- 0
ice_shelf_top_p:
- 20
- 0.95
- 0
boundary_layer_thickness: .01
store_solutions: true
