final_time: 240
steps_n: 30    # dt = 1/30 h = 120 s  (kimura 200 s)
simulation_precision: -7
g: 9.81
nu: 
- 0.25
- 0.001
alpha:
- 0.25 #- 0.25
- 0.00002 #- 0.00002
rho_0: 1000
beta: 0.00004
gamma: 0.0008
T_0: 0.4
S_0: 35
max_iter: 0
BCs:
    V:
        right: [0,0]
        bottom: [0,0]
        ice_shelf: [0,0]
        left: [0,0]
        top: ['null',0]
    T:
        #ice_shelf: -0.7 #output values from john's setup
        right: 0.4
    Q:
        '(5,1)': 0
    S:
        #ice_shelf: 34.82 #output values from john's setup
        right: 35
melt_boundaries:
    - ice_shelf
convert_from_ms_to_kmh: True
very_verbose: True
stabilization_NS: True
stabilization_T: True
stabilization_S: True
checkpoint_interval: 50
plot_path: mitgcm-pygmsh-nice-mesh
domain_size_x: 2.2
domain_size_y: 0.43
mesh_resolution: 10
ice_shelf_bottom_p:
- 0
- 0.05
- 0
ice_shelf_top_p:
- 2
- 0.41
- 0
boundary_layer_thickness: .01
store_solutions: true
