final_time: 1000000 # to convergence
steps_n: 350
g: 1
nu: 
- 1
alpha:
- 1
rho_0: 1
beta: 2500
gamma: 0
T_0: 0
domain: fjord
domain_size_x: 4
domain_size_y: 1
shelf_size_x: 0
shelf_size_y: 0
mesh_resolution_x: 60
mesh_resolution_y: 25
mesh_resolution_sea_y: 1
BCs:
    V:
        right: [0,'null']
        bottom: [0,0]
        left: [0,'null']
        sea_top: [0,0]
    Q:
        (0,0): 0
    T:
        sea_top: 0
        bottom: 1
