final_time: 10
steps_n: 10000
simulation_precision: -3
g: 127000
nu:
- 1
alpha:
- 0.36
rho_0: 79
beta: 0.0001
gamma: 0.00076
T_0: 1
S_0: 35
domain: square
mesh_resolution: 10
max_iter: 0
BCs:
    V:
        right: ['0.5*sin(2*pi*x[1])', 0]
        bottom: [0,0]
        left: [0,0]
        top: [0,0]
    T:
        right: 3
        left: -1.9
    Q:
        '(1,1)': 0
    S:
        right: 35
        left: 34.5
