final_time: 10
steps_n: 10000
simulation_precision: -3
g: 9.81
nu: 
- 100
alpha:
- 100
rho_0: 1028
beta: 0.0001
gamma: 0
T_0: 1
domain: fjord
domain_size_x: 3
domain_size_y: 3
shelf_size_x: 0
shelf_size_y: 0
mesh_resolution_x: 30
mesh_resolution_y: 30
store_solutions: True
max_iter: 5
plot_path: 'out/'
BCs:
    V:
        right: ['10*0.14*sin(2/3*pi*x[1])', 0]
        bottom: [0,0]
        left: [0,0]
        sea_top: ['null', 0]
    Q:
        '(3,3)': 0
    T:
        right: 1
        left: 0
    S:
        right: 35
        left: 34.5
