final_time: 10
steps_n: 10000
simulation_precision: -3
g: 1
nu: 
- 1
alpha:
- 1
rho_0: 1
beta: 1000
gamma: 0
T_0: 0
S_0: 35
domain: square
domain_size_x: 2
domain_size_y: 1
shelf_size_x: 0.7
shelf_size_y: 0.1
mesh_resolution: 10
mesh_resolution_x: 20
mesh_resolution_y: 10
mesh_resolution_sea_y: 1
store_solutions: False
label: ''
max_iter: 0
BCs:
    V:
        right: [0,0]
        bottom: [0,0]
        left: [0,0]
        top: [0,0]
    T:
        right: 0
        left: 1
    S:
        right: 35
        left: 34.5
