final_time: 10
steps_n: 10000
precision: -3
g: 9.81
nu: 
- 100
alpha:
- 100
rho_0: 1028
beta: 0.0001
gamma: 0.00076
T_0: 1
S_0: 35
ocean_bc: 0.5
domain: custom
domain_size_x: 2
domain_size_y: 1
shelf_size_x: 0.7
shelf_size_y: 0.1
mesh_resolution: 10
mesh_resolution_x: 20
mesh_resolution_y: 10
mesh_resolution_sea_top_y: 1
store_sol: False
verbose: True
very_verbose: False
plot: True
label: ''
max_iter: 0
